pipeline:
  name: brain-mri-train
description: Detects changed files into a repository and triggers a retraining on that dataset
input:
  pfs:
    name: mri_raw_data
    repo: mri_raw_data
    branch: branch_v1
    glob: /
    empty_files: false
reprocess_spec: every_job                          # reprocess every datum even the input datums have not change. Another value is "until_success" and "every_job"
transform:
  cmd: # the cmd is repeatedly executed for every datum under the same job.
    - sh
    - "-c"
    - "git clone https://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@github.com/boon1987/brain_mri.git /code && python3 /code/pds_version/container/train/train.py --git-url https://git@github.com:/hpelabssg/pdk-use-cases.git --git-ref main --sub-dir brain-mri/experiment --pach_config '/code/pds_version/pipelines/training-pipeline.yml' --config const.yaml --pach_project_name 'Brain-MRI' --repo mri_raw_data --branch 'branch_v1' --model brain-mri --work-dir /code/pds_version/experiment && rm -rf /code"  #cmd:
  #    - /bin/sh
  #stdin:
  #    - 'python train.py --git-url https://git@github.com:/hpelabssg/pdk-use-cases.git --git-ref main --sub-dir brain-mri/experiment --config const.yaml --repo brain-mri-data --model brain-mri --project pdk-brain-mri'
  #image: "hpelabssg/pds:train_0.0.1"
  image: "hpelabssg/pdk:train_0.0.1"
  secrets:
    - name: pachyderm-determined-pipeline-secret
      key: det_master
      env_var: DET_MASTER
    - name: pachyderm-determined-pipeline-secret
      key: det_user
      env_var: DET_USER
    - name: pachyderm-determined-pipeline-secret
      key: det_password
      env_var: DET_PASSWORD
    - name: pachyderm-determined-pipeline-secret
      key: pac_token
      env_var: PAC_TOKEN
    - name: pachyderm-determined-pipeline-secret
      key: pachyderm_host
      env_var: PACHD_LB_SERVICE_HOST
    - name: pachyderm-determined-pipeline-secret
      key: pachyderm_port
      env_var: PACHD_LB_SERVICE_PORT
pod_patch: '[{"op": "add","path": "/volumes/-","value": {"name": "task-pv-storage","persistentVolumeClaim": {"claimName": "task-det-checkpoints-pvc"}}}, {"op": "add","path": "/containers/0/volumeMounts/-","value": {"mountPath": "/determined_shared_fs","name": "task-pv-storage"}}]'
