name: MRI-const
#project: "Brain MRI"
#workspace: khanghua.boon
data:
  data_dir:  '/run/determined/workdir/shared_fs/brain_mri_dataset'
  repo: 'mateuszbuda/brain-segmentation-pytorch'
  model: 'unet'
hyperparameters:
  global_batch_size: 32
  init_features: 32
  input_channels: 3
  output_channels: 1
  learning_rate: 0.001
  weight_decay: 0.0
  pretrained: True # starting from pretrained unet model from PyTorch Hub
  split_seed: 1
  validation_ratio: 0.2
  
  # data augmentation hyperparameters
  hflip_augmentation: True
  affine_augmentation: True
  max_rotation: 15 # images can be rotated by up to this number of degrees, in either direction
  max_translation: 0.1
  min_scale: 0.8
  max_scale: 1.2
records_per_epoch: 3143
searcher:
  name: single
  metric: val_dice
  smaller_is_better: False
  max_length:
    epochs: 10
min_validation_period:
  epochs: 1
resources:
  slots_per_trial: 1
max_restarts: 0
entrypoint: model_def:MRIUnetTrial
#entrypoint: python3 -m determined.launch.horovod --trial model_def:MRIUnetTrial
#entrypoint: python3 -m determined.launch.torch_distributed -- --trial model_def:MRIUnetTrial
#det -m 10.90.1.51 e create ./src/const.yaml ./src
#entrypoint: python3 -m determined.launch.torch_distributed -- --trial model_def:MRIUnetTrial

# bind_mounts:
#   - host_path: /mnt/efs
#     container_path: /data
#     read_only: True
bind_mounts: 
  - container_path: /run/determined/workdir/shared_fs
    host_path: /mnt/mapr_nfs/determined 
    propagation: rprivate 
    read_only: false 