pipeline:
    name: Edge-Detection-Pipeline                    # pipeline name
description: Perform edge detection on images.     # pipeline description
output_branch: branch_v1                           # branch name of the output commit
input:
    pfs:
        name: pipeline_input_data                  # Replace repo@branch with this name. Both paths "pfs/pipeline_input_data" & "pfs/out" are mounted on the k8s pod container.
        repo: Input_Training_Dataset
        branch: branch_v1                          # specify which branch of the repo as the input to the pipeline during executing the job/datum.
        glob: /*/*                                    # specify the datum shape, which in turn affect the data parallelism.
        empty_files: false                         # ?
autoscaling: true                                  # automatic scale-up and scale-down number of the workers, with maximum specified by "parallelism_spec".
parallelism_spec:
    constant: 3
reprocess_spec: until_success                          # reprocess every datum even the input datums have not change. Another value is "until_success" and "every_job"
transform:
    cmd:                                           # the cmd is repeatedly executed for every datum under the same job.
        - sh
        - '-c'
        - 'git clone https://github.com/boon1987/brain_mri.git /code && python3 /code/pds_version/edge_detection_pipeline/edges.py && rm -rf /code'
    image: 'pachyderm/opencv:1.0'                  # image to be run
    stdin:
        - cat /code/pds_version/edge_detection_pipeline/edges.py
    secrets:
        - name: pachyderm-determined-secret
          key: determined-master
          env_var: DET_MASTER
        - name: pachyderm-determined-secret
          key: determined-username
          env_var: DET_USER
        - name: pachyderm-determined-secret
          key: determined-password
          env_var: DET_PASSWORD
        - name: pachyderm-determined-secret
          key: pachyderm-host
          env_var: PACHD_LB_SERVICE_HOST
        - name: pachyderm-determined-secret
          key: pachyderm-port
          env_var: PACHD_LB_SERVICE_PORT
pod_patch: '[{"op": "add","path": "/volumes/-","value": {"name": "det-checkpoints","hostpath": {"path": "/mnt/mapr_nfs/determined/checkpoints","type": "DirectoryOrCreate"}}}, {"op": "add","path": "/containers/0/volumeMounts/-","value": {"mountPath": "/determined_shared_fs","name": "det-checkpoints"}}]'
